package ch.trancee.kompact.ksp

import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration

/**
 * Spec: .scratch/kompact-spec/issues/02-generation-strategy.md
 *        .scratch/kompact-spec/issues/06-validation-model.md
 *
 * Kompact KSP processor. For each `@KompactModel` class:
 *  1. Builds a [LayoutModel] and validates structural invariants
 *     (Ticket 06) — bit-offset overlap, length-prefix width,
 *     enum-width, etc.
 *  2. Emits a common `expect value class <ModelName>View` into
 *     `commonMain` so generated views are visible to all targets.
 *
 * KSP `#567` (open as of Kotlin 2.3) prevents the processor from
 * emitting per-target actuals into the correct source set from a
 * `kspCommonMainMetadata` invocation. v1 of this processor emits
 * only the common expect; the per-target actuals are the consumer's
 * responsibility (a small set of per-target hand-written stubs, or a
 * follow-up KSP round targeting `kspKotlinJvm` / `kspIosArm64`).
 */
class KompactProcessor(
    private val environment: SymbolProcessorEnvironment,
) : SymbolProcessor {

    private val codeGenerator = environment.codeGenerator
    private val logger = environment.logger
    private val emitted = mutableSetOf<String>()
    private var annotationsEmitted = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("ch.trancee.kompact.annotation.KompactModel")
        val models = mutableListOf<KSClassDeclaration>()
        for (symbol in symbols) {
            if (symbol is KSClassDeclaration && symbol.classKind == ClassKind.CLASS) {
                models.add(symbol)
            }
        }
        for (model in models) {
            try {
                processModel(resolver, model)
            } catch (t: Throwable) {
                logger.error("KompactProcessor failed on ${model.simpleName.asString()}: ${t.message}", model)
            }
        }
        if (!annotationsEmitted && models.isNotEmpty()) {
            emitAnnotationsStub()
            annotationsEmitted = true
        }
        return emptyList()
    }

    private fun processModel(resolver: Resolver, model: KSClassDeclaration) {
        val modelName = model.simpleName.asString()
        val viewName = "${modelName}View"
        val packageName = model.packageName.asString()

        val fieldAnnotation = resolver
            .getClassDeclarationByName("ch.trancee.kompact.annotation.KompactField")
        val fields = model.getAllProperties()
            .toList()
            .filter { prop -> prop.annotations.any { it.matches(fieldAnnotation) } }
            .mapNotNull { prop ->
                val ann = prop.annotations.first { it.matches(fieldAnnotation) }
                KompactFieldInfo.from(prop, ann)
            }

        val layout = LayoutModel.build(viewName, fields)
        if (!layout.validate(logger, model)) return

        emitCommonExpect(packageName, viewName, fields)
    }

    private fun KSAnnotation.matches(
        classDecl: com.google.devtools.ksp.symbol.KSClassDeclaration?,
    ): Boolean {
        if (classDecl == null) return false
        val annDecl = annotationType.resolve().declaration
        return annDecl.qualifiedName?.asString() == classDecl.qualifiedName?.asString()
    }

    private fun emitCommonExpect(
        packageName: String,
        viewName: String,
        fields: List<KompactFieldInfo>,
    ) {
        val key = "common_$viewName"
        if (!emitted.add(key)) return
        val src = buildString {
            appendLine("// Generated by KompactProcessor — DO NOT EDIT.")
            appendLine("package $packageName")
            appendLine()
            append("public expect value class $viewName(val raw: ByteArray) {\n")
            for (f in fields) {
                appendLine("    ${f.accessorDeclaration()}")
            }
            appendLine("}")
        }
        writeAggregating("common", "$viewName.kt", src)
    }

    private fun emitAnnotationsStub() {
        val src = """
            // Generated by KompactProcessor — DO NOT EDIT.
            package ch.trancee.kompact.annotation

            @Target(AnnotationTarget.CLASS)
            @Retention(AnnotationRetention.SOURCE)
            public annotation class KompactModel

            @Target(AnnotationTarget.PROPERTY)
            @Retention(AnnotationRetention.SOURCE)
            public annotation class KompactField(
                val bitOffset: Int,
                val bitWidth: Int,
                val lengthPrefixBits: Int = 0,
                val enumWidth: Int = 0,
                val defaultValue: Int = 0,
            )
        """.trimIndent()
        writeAggregating("common", "KompactAnnotations.kt", src)
    }

    private fun writeAggregating(sourceSetSuffix: String, fileName: String, content: String) {
        val name = "kompact_${sourceSetSuffix}_${fileName.substringBeforeLast(".").lowercase()}"
        val ext = fileName.substringAfterLast(".")
        val file = try {
            codeGenerator.createNewFile(
                dependencies = Dependencies(aggregating = true),
                packageName = "ch.trancee.kompact.generated",
                fileName = name,
                extensionName = ext,
            )
        } catch (e: FileAlreadyExistsException) {
            return
        }
        file.bufferedWriter().use { it.write(content) }
    }
}

class KompactProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        KompactProcessor(environment)
}
