[versions]
kotlin = "2.4.20"
ksp = "2.3.11"
bcv = "0.18.2"
dokka = "2.2.0"
kover = "0.9.9"
spotless = "8.10.2"
skie = "0.10.14"

[plugins]
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
bcv = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
kotlinPowerAssert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }

[libraries]
kotlinPowerAssert = { module = "org.jetbrains.kotlin:kotlin-power-assert", version.ref = "kotlin" }
