complexity:
  CyclomaticComplexMethod:
    threshold: 25
  LongMethod:
    threshold: 180
    excludes: ["**/test/**", "**/commonTest/**"]
  TooManyFunctions:
    thresholdInClasses: 20
    thresholdInFiles: 25
    thresholdInInterfaces: 20
    thresholdInObjects: 20

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 240
  ReturnCount:
    max: 4
